name: Build Firmware

on:
  workflow_call:
    inputs:
      platform:
        required: true
        type: string
      board:
        required: true
        type: string

permissions: read-all

jobs:
  build-stm32:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4

      - name: Get release version string
        shell: bash
        run: echo "long=$(./bin/buildinfo.py long)" >> $GITHUB_OUTPUT
        id: version

      - name: Build ${{ inputs.platform }}
        id: build
        uses: meshtastic/gh-action-firmware@main
        env:
          generic_plat: >-
            ${{ startsWith(inputs.platform, 'esp32') && 'esp32' || startsWith(inputs.platform, 'nrf52') && 'nrf52' || inputs.platform }}
        with:
          pio_platform: ${{ env.generic_plat }}
          pio_env: ${{ inputs.board }}
          pio_target: build

      - name: Store binaries as an artifact
        uses: actions/upload-artifact@v4
        with:
          name: firmware-${{ inputs.platform }}-${{ inputs.board }}-${{ steps.version.outputs.long }}.zip
          overwrite: true
          path: |
            release/*.uf2
            release/*.hex
            release/*.bin
            release/*.elf
            release/*-ota.zip
